name: Robot CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  Robot-Framework-Testes:
    runs-on: ubuntu-latest
    steps:
    # Permissão de todo o projeto 
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    # Instalação de dependencias do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    
    # Execução dos testes do robot
    - name: Robot Framework - Tests
      if: always()
      run: robot -d results $GITHUB_WORKSPACE/AutomacaoWeb/tests/*.robot
      
    # Etapa de geração de um report personalizado
    - name: Download robotmetrics
      if: always()
      run: |
        cd results
        robotmetrics
        
    # Etapa de publicação do report em uma pasta no projeto chamada results
    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robot-test-results
        path: results
